[package]
name = "bond"
version = "0.1.0"
authors = ["Boban Acimovic <boban.acimovic@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
confy = { version = "^0.4", default-features = false, features = ["yaml_conf"] }
env_logger = "0.8"
futures = "0.3"
k8s-openapi = { version = "0.10", default-features = false, features = ["v1_19"] }
kube = "0.44"
kube-runtime = "0.44"
log = "0.4"
serde = "^1.0"
serde_derive = "^1.0"
tokio = { version = "0.2", features = ["full"] }

[patch.crates-io]
confy = { git = 'https://github.com/rust-cli/confy' }
