[package]
name = "bond"
version = "0.1.0"
authors = ["Boban Acimovic <boban.acimovic@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kube = "0.44"
kube-runtime = "0.44"
k8s-openapi = { version = "0.10", default-features = false, features = ["v1_19"] }
log = "0.4"
futures = "0.3"
tokio = { version = "0.2", features = ["full"] }
env_logger = "0.8"
anyhow = "1.0"
